src/Entity/Persona.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * Persona
 *
 * @ORM\Table(name="Persona")
 * @ORM\Entity
 */
class Persona
{
    /**
     * @var int
     *
     * @ORM\Column(name="Id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="RUN", type="string", length=15, nullable=true)
     */
    private $run;

    /**
     * @var string
     *
     * @ORM\Column(name="Nombres", type="string", length=255, nullable=true)
     */
    private $nombres;

    /**
     * @var string
     *
     * @ORM\Column(name="Apellido_Paterno", type="string", length=255, nullable=true)
     */
    private $apellidoPaterno;

    /**
     * @var string
     *
     * @ORM\Column(name="Apellido_Materno", type="string", length=255, nullable=true)
     */
    private $apellidoMaterno;

    /**
     * @var string
     *
     * @ORM\Column(name="Ocupacion", type="string", length=255, nullable=true)
     */
    private $ocupacion;

    /**
     * @var string
     *
     * @ORM\Column(name="Genero", type="string", length=255, nullable=true)
     */
    private $genero;

    /**
     * @var string
     *
     * @ORM\Column(name="Estado_Civil", type="string", length=255, nullable=true)
     */
    private $estadoCivil;

    /**
     * @var string
     *
     * @ORM\Column(name="Nacionalidad", type="string", length=255, nullable=true)
     */
    private $nacionalidad;

    /**
     * @var string
     *
     * @ORM\Column(name="Lugar_Nacimiento", type="string", length=255, nullable=true)
     */
    private $lugarNacimiento;

    /**
     * @ORM\Column(name="Fecha_Nacimiento", type="date", nullable=true)
     */
    private $fechaNacimiento;

    /**
     * @var \PersonaAccidente
     *
     * @ORM\OneToOne(targetEntity="PersonaAccidente", mappedBy="persona")
     */
    private $personaAccidente;

    /**
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(name="Registrado", type="datetime")
     */
    private $registrado;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRun(): ?string
    {
        return $this->run;
    }

    public function setRun(?string $run): self
    {
        $this->run = $run;

        return $this;
    }

    public function getNombres(): ?string
    {
        return $this->nombres;
    }

    public function setNombres(?string $nombres): self
    {
        $this->nombres = $nombres;

        return $this;
    }

    public function getApellidoPaterno(): ?string
    {
        return $this->apellidoPaterno;
    }

    public function setApellidoPaterno(?string $apellidoPaterno): self
    {
        $this->apellidoPaterno = $apellidoPaterno;

        return $this;
    }

    public function getApellidoMaterno(): ?string
    {
        return $this->apellidoMaterno;
    }

    public function setApellidoMaterno(?string $apellidoMaterno): self
    {
        $this->apellidoMaterno = $apellidoMaterno;

        return $this;
    }

    public function getGenero(): ?string
    {
        return $this->genero;
    }

    public function setGenero(?string $genero): self
    {
        $this->genero = $genero;

        return $this;
    }

    public function getLugarNacimiento(): ?string
    {
        return $this->lugarNacimiento;
    }

    public function setLugarNacimiento(?string $lugarNacimiento): self
    {
        $this->lugarNacimiento = $lugarNacimiento;

        return $this;
    }

    public function getOcupacion(): ?string
    {
        return $this->ocupacion;
    }

    public function setOcupacion(?string $ocupacion): self
    {
        $this->ocupacion = $ocupacion;

        return $this;
    }

    public function getEstadoCivil(): ?string
    {
        return $this->estadoCivil;
    }

    public function setEstadoCivil(string $estadoCivil): self
    {
        $this->estadoCivil = $estadoCivil;

        return $this;
    }

    public function getNacionalidad(): ?string
    {
        return $this->nacionalidad;
    }

    public function setNacionalidad(string $nacionalidad): self
    {
        $this->nacionalidad = $nacionalidad;

        return $this;
    }

    /**
     * @return Collection|PersonaAccidente[]
     */
    public function getPersonaAccidente(): Collection
    {
        return $this->personaAccidente;
    }

    public function setPersonaAccidente(?PersonaAccidente $personaAccidente): self
    {
        $this->personaAccidente = $personaAccidente;

        // set (or unset) the owning side of the relation if necessary
        $newPersona = $personaAccidente === null ? null : $this;
        if ($newPersona !== $personaAccidente->getPersona()) {
            $personaAccidente->setPersona($newPersona);
        }

        return $this;
    }

    public function getFechaNacimiento(): ?\DateTimeInterface
    {
        return $this->fechaNacimiento;
    }

    public function setFechaNacimiento(\DateTimeInterface $fechaNacimiento): self
    {
        $this->fechaNacimiento = $fechaNacimiento;

        return $this;
    }

    public function estaVacio(): bool
    {
        if ($this->getRun()) {
            return false;
        } elseif($this->getNombres()) {
            return false;
        } elseif($this->getApellidoPaterno()) {
            return false;
        } elseif($this->getApellidoMaterno()) {
            return false;
        } elseif($this->getOcupacion()) {
            return false;
        } elseif($this->getLugarNacimiento()) {
            return false;
        } else {
            return true;
        }
    }

    public function getRegistrado(): ?\DateTimeInterface
    {
        return $this->registrado;
    }

    public function setRegistrado(\DateTimeInterface $registrado): self
    {
        $this->registrado = $registrado;

        return $this;
    }

    public function getEdad(): ?\DateInterval
    {
        return $this->getFechaNacimiento() ? $this->getFechaNacimiento()->diff($this->getRegistrado()) : NULL;
    }

}

src/Form/PersonaType.php
<?php

namespace App\Form;

use App\Entity\Persona;
use App\Entity\Nacionalidad;
use App\Entity\EstadoCivil;
use App\Validator\Rut;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\BirthdayType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Validator\Constraints\NotBlank;

class PersonaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('run', TextType::class, [
                'label' => 'persona.run',
                'attr' => [ 'class' => 'rut' ],
                'constraints' => array(new Rut()),
                'required' => false,
            ])
            ->add('nombres', TextType::class, [
                'label' => 'persona.nombres',
                'attr' => [ 'class' => 'nombre-propio' ],
                'required' => false,
            ])
            ->add('apellidoPaterno', TextType::class, [
                'label' => 'persona.apellidoPaterno',
                'attr' => [ 'class' => 'nombre-propio' ],
                'required' => false,
            ])
            ->add('apellidoMaterno', TextType::class, [
                'label' => 'persona.apellidoMaterno',
                'attr' => [ 'class' => 'nombre-propio' ],
                'required' => false,
            ])
            ->add('ocupacion', TextType::class, [
                'label' => 'persona.ocupacion',
                'attr' => [ 'class' => 'nombre-propio' ],
                'required' => false,
            ])
            ->add('lugarNacimiento', TextType::class, [
                'label' => 'persona.lugarNacimiento',
                'attr' => [ 'class' => 'nombre-propio' ],
                'required' => false,
            ])
            ->add('fechaNacimiento', BirthdayType::class, [
                'label' => 'persona.fechaNacimiento',
            ])
            ->add('genero', ChoiceType::class, [
                'label' => 'persona.genero',
                'choices' => [
                    'No determinado' => 'No determinado',
                    'Masculino' => 'Masculino',
                    'Femenino' => 'Femenino',
                ],
                'attr' => [ 'class' => 'simple-select' ],
                'placeholder' => 'Seleccione',
                'required' => true,
            ])
            ->add('estadoCivil', ChoiceType::class, [
                'label' => 'persona.estadoCivil',
                'choices' => [
                    'No determinado' => 'No determinado',
                    'Soltero(a)' => 'Soltero(a)',
                    'Casado(a)' => 'Casado(a)',
                    'Divorciado(a)' => 'Divorciado(a)',
                    'Viudo(a)' => 'Viudo(a)',
                ],
                'attr' => [ 'class' => 'simple-select' ],
                'placeholder' => 'Seleccione',
                'required' => true,
            ])
            ->add('nacionalidad', ChoiceType::class, [
                'label' => 'persona.nacionalidad',
                'choices' => [
                    'No determinada' => 'No determinada',
                    'Chilena' => 'Chilena',
                    'Venezolana' => 'Venezolana',
                    'Peruana' => 'Peruana',
                    'Haitiana' => 'Haitiana',
                    'Colombiana' => 'Colombiana',
                    'Boliviana' => 'Boliviana',
                    'Argentina' => 'Argentina',
                    'Ecuatoriana' => 'Ecuatoriana',
                    'Española' => 'Española',
                    'Brasileña' => 'Brasileña',
                    'Dominicana' => 'Dominicana',
                    'Estadounidense' => 'Estadounidense',
                    'Cuabana' => 'Cuabana',
                    'China' => 'China',
                    'Mejicana' => 'Mejicana',
                    'Alemana' => 'Alemana',
                    'Otra latinoamericana' => 'Otra latinoamericana',
                    'Otra norteamericana' => 'Otra norteamericana',
                    'Otra europea' => 'Otra europea',
                    'Otra del mundo' => 'Otra del mundo',
                ],
                'attr' => [ 'class' => 'simple-select' ],
                'placeholder' => 'Seleccione',
                'required' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Persona::class,
        ]);
    }
}

src/Controller/InspeccionController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/inspeccion")
 */
class InspeccionController extends AbstractController
{
    /**
     * @Route("/index", name="inspeccion_index", methods={"GET"})
     */
    public function index(Request $request): Response
    {
        return $this->render('inspeccion/index.html.twig');
    }

    /**
     * @Route("/vehiculo/filtrar", name="inspeccion_vehiculo_filtrar", methods={"GET", "POST"})
     */
    public function vehiculoFiltrar(Request $request): Response
    {
        $filtros = $this->get('session')->has('filtroInspeccionVehiculo') ? $this->get('session')->get('filtroInspeccionVehiculo') : null;

        $this->manageObjects($filtros);

        $form = $this->createForm(FiltroInspeccionType::class, $filtros);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->get('session')->set('filtroInspeccionVehiculo', $form->getData());
            return $this->redirectToRoute('inspeccion_vehiculo_index');
        }

        return $this->render('inspeccion/vehiculo/filtrar.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/persona/filtrar", name="inspeccion_persona_filtrar", methods={"GET", "POST"})
     */
    public function personaFiltrar(Request $request): Response
    {
        $filtros = $this->get('session')->has('filtroInspeccionPersona') ? $this->get('session')->get('filtroInspeccionPersona') : null;

        $this->manageObjects($filtros);

        $form = $this->createForm(FiltroPersonaType::class, $filtros);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->get('session')->set('filtroInspeccionPersona', $form->getData());
            return $this->redirectToRoute('inspeccion_persona_index');
        }

        return $this->render('inspeccion/persona/filtrar.html.twig', [
            'form' => $form->createView(),
        ]);
    }


}

templates/inspeccion/persona/exportar.html.twig
{% extends 'inspeccion/persona/layout.html.twig' %}

{% block title %}Exportar búsqueda de personas{% endblock %}

{% block header %}
    <h1><span class="fa fa-fw fa-search"></span> Inspección - Exportar búsqueda de personas</h1>
{% endblock %}

{% block persona %}
    <div class="row">
        <div class="col">
            <div class="card mb-2">
                <div class="card-header">
                    {% set menu = knp_menu_get('inspeccionPersonas', [], {}) %}
                    {{ knp_menu_render(menu) }}
                </div>
                <div class="card-body">
                    {% form_theme form 'bootstrap_4_horizontal_layout.html.twig' _self %}
                    {{ form_start(form) }}
                    <div class="form-row">
                        <div class="col-xl-12">
                            {{ form_row(form.submit) }}
                        </div>
                    </div>

                    <div class="form-row">
                        <div class="col-xl-4">

                            <div class="card mb-2">
                                <div class="card-header">Información personal</div>
                                <div class="card-body">
                                {{ form_row(form.run) }}
                                {{ form_row(form.nombres) }}
                                {{ form_row(form.apellidoPaterno) }}
                                {{ form_row(form.apellidoMaterno) }}
                                {{ form_row(form.ocupacion) }}
                                {{ form_row(form.genero) }}
                                {{ form_row(form.estadoCivil) }}
                                {{ form_row(form.nacionalidad) }}
                                {{ form_row(form.lugarNacimiento) }}
                                {{ form_row(form.fechaNacimiento) }}
                                </div>
                            </div>

                            <div class="card mb-2">
                                <div class="card-header">Situación personal</div>
                                <div class="card-body">
                                {{ form_row(form.edad) }}
                                {{ form_row(form.calidadPersona) }}
                                {{ form_row(form.claseLicencia) }}
                                {{ form_row(form.comunaLicencia) }}
                                {{ form_row(form.condicionFisica) }}
                                {{ form_row(form.consecuenciaPersona) }}
                                {{ form_row(form.cualidadEspecial) }}
                                {{ form_row(form.tipoTrayecto) }}
                                {{ form_row(form.seguridad) }}
                                {{ form_row(form.personaEsCausanteProbable) }}
                                {{ form_row(form.personaSeFuga) }}
                                </div>
                            </div>
                        </div>

                        <div class="col-xl-4">
                            <div class="card mb-2">
                                <div class="card-header">Información vehicular</div>
                                <div class="card-body">
                                {{ form_row(form.placaPatenteUnica) }}
                                {{ form_row(form.marcaVehiculo) }}
                                {{ form_row(form.modeloVehiculo) }}
                                {{ form_row(form.ano) }}
                                {{ form_row(form.color) }}
                                {{ form_row(form.tipoVehiculo) }}
                                </div>
                            </div>

                            <div class="card mb-2">
                                <div class="card-header">Situación vehicular</div>
                                <div class="card-body">
                                {{ form_row(form.direccionVehiculo) }}
                                {{ form_row(form.servicioVehiculo) }}
                                {{ form_row(form.maniobraVehiculo) }}
                                {{ form_row(form.consecuenciaVehiculo) }}
                                {{ form_row(form.vehiculoEsCausanteProbable) }}
                                {{ form_row(form.vehiculoSeFuga) }}
                                </div>
                            </div>
                        </div>

                        <div class="col-xl-4">
                            <div class="card mb-2">
                                <div class="card-header">Información del accidente</div>
                                <div class="card-body">
                                {{ form_row(form.id) }}
                                {{ form_row(form.fecha) }}
                                {{ form_row(form.hora) }}
                                {{ form_row(form.claseAccidente) }}
                                {{ form_row(form.tipoAccidente) }}
                                {{ form_row(form.causaBasal) }}
                                {{ form_row(form.creado) }}
                                {{ form_row(form.actualizado) }}
                                </div>
                            </div>

                            <div class="card mb-2">
                                <div class="card-header">Información territorial</div>
                                <div class="card-body">
                                {{ form_row(form.region) }}
                                {{ form_row(form.provincia) }}
                                {{ form_row(form.comuna) }}
                                </div>
                            </div>
                        </div>

{#}

                        <div class="col-xl-4">
                            <div class="card mb-2">
                                <div class="card-header">Información relativa</div>
                                <div class="card-body">
                                {{ form_row(form.tipoDireccion) }}
                                {{ form_row(form.tipoUbicacionRelativaAccidente) }}
                                {{ form_row(form.tipoZonaAccidente) }}
                                </div>
                            </div>
                        </div>
{#}

{#}
                        <div class="col-xl-4">
                            <div class="card mb-2">
                                <div class="card-header">Información espacial</div>
                                <div class="card-body">
                                {{ form_row(form.glosa) }}
                                {{ form_row(form.calle) }}
                                {{ form_row(form.numero) }}
                                {{ form_row(form.direccion) }}
                                {{ form_row(form.latitud) }}
                                {{ form_row(form.longitud) }}
                                {{ form_row(form.maestroId) }}
                                {{ form_row(form.tipoId) }}
                                {{ form_row(form.tipo) }}
                                {{ form_row(form.pais) }}
                                {{ form_row(form.comuna) }}
                                </div>
                            </div>

                        </div>
{#}
                    </div>
                    {{ form_rest(form) }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block form_label_class -%}col-sm-0{%- endblock form_label_class %}

{% block form_group_class -%}col-sm-12{%- endblock form_group_class %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('inspeccion') }}
{% endblock %}

templates/inspeccion/persona/filtrar.html.twig
{% extends 'inspeccion/persona/layout.html.twig' %}

{% block title %}Filtrar personas{% endblock %}

{% block header %}
    <h1><span class="fa fa-fw fa-search"></span> Inspección - Filtrar personas</h1>
{% endblock %}

{% block persona %}
    <div class="row">
        <div class="col">
            <div class="card mb-2">
                <div class="card-header border-bottom-0">
                    {% set menu = knp_menu_get('inspeccionPersonas', [], {}) %}
                    {{ knp_menu_render(menu) }}
                </div>
            </div>
        </div>
    </div>

    {% form_theme form 'bootstrap_4_horizontal_layout.html.twig' _self %}
    {{ form_start(form) }}
    <div class="row">

        <div class="col-12">
            <div class="card mb-2">
                <div class="card-header">Información personal</div>
                <div class="card-body">
                {{ form_row(form.condicionFisica) }}
                {{ form_row(form.consecuenciaPersona) }}
                {{ form_row(form.cualidadEspecial) }}
                {{ form_row(form.tipoTrayecto) }}
                {{ form_row(form.seguridad) }}
                {{ form_row(form.claseLicencia) }}
                {{ form_row(form.comunaLicencia) }}
                </div>
            </div>
        </div>

        <div class="col-12">
            <div class="card mb-2">
                <div class="card-header">Información vehicular</div>
                <div class="card-body">
                {{ form_row(form.tipoVehiculo) }}
                {{ form_row(form.servicioVehiculo) }}
                {{ form_row(form.maniobraVehiculo) }}
                {{ form_row(form.direccionVehiculo) }}
                {{ form_row(form.consecuenciaVehiculo) }}
                </div>
            </div>
        </div>

        <div class="col-12">
            <div class="card mb-2">
                <div class="card-header">Información territorial</div>
                <div class="card-body">
                {{ form_row(form.region) }}
                {{ form_row(form.provincia) }}
                {{ form_row(form.comuna) }}
                </div>
            </div>
        </div>

        <div class="col-12">
            <div class="card mb-2">
                <div class="card-header">Información cualitativa</div>
                <div class="card-body">
                {{ form_row(form.claseAccidente) }}
                {{ form_row(form.tipoAccidente) }}
                {{ form_row(form.causaBasal) }}
                {{ form_row(form.causas) }}
                </div>
            </div>
        </div>

        <div class="col-12">
            {{ form_widget(form.submit, {attr: {'class' : 'btn btn-primary btn-block'}}) }}
        </div>

    </div>
    {{ form_rest(form) }}

{% endblock %}

{% block form_label_class -%}col-sm-2 text-md-right{%- endblock form_label_class %}

{% block form_group_class -%}col-sm-10{%- endblock form_group_class %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('inspeccion') }}
{% endblock %}

templates/inspeccion/persona/index.html.twig
{% extends 'inspeccion/persona/layout.html.twig' %}

{% block title %}Búsqueda de personas{% endblock %}

{% block header %}
    <h1><span class="fa fa-fw fa-search"></span> Inspección - Búsqueda de personas</h1>
{% endblock %}

{% block persona %}
    <div class="row">
        <div class="col">
            <div class="card mb-2">
                <div class="card-header">
                    {% set menu = knp_menu_get('inspeccionPersonas', [], {}) %}
                    {{ knp_menu_render(menu) }}
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-2">
                            <button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#exampleModal"><span class="fa fa-search"></span> Ver consulta SQL</button>
                            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog modal-lg" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Consulta SQL</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                        </div>
                                        <div class="modal-body"><pre class="prettyprint"><code class="language-sql">{{ sql|replace({', ': ',\n', 'LEFT JOIN': '\nLEFT JOIN', 'WHERE': '\nWHERE', 'AND': '\nAND'}) }}</code></pre></div>
                                        {% if parameters is iterable %}{% set matrix = [] %}{% for parameter in parameters %}{% if parameter.value is iterable %}{% set array = [] %}{% for entity in parameter.value %}{% set array = array|merge([entity.id]) %}{% endfor %}{% set matrix = matrix|merge({ (parameter.name) : array} ) %}{% elseif parameter.value is instanceof('DateTime') %}{% set matrix = matrix|merge({ (parameter.name) : ('"' ~ parameter.value|date('d-m-Y') ~ '"')} ) %}{% else %}{% set matrix = matrix|merge({ (parameter.name) : ('"' ~ parameter.value ~ '"') } ) %}{% endif %}{% endfor %}{% endif %}
                                        <div class="modal-body">
                                            {% for key, parameter in matrix %}
                                                {{ ('inspeccion.' ~ key)|trans }}: {{ parameter|join(', ') }}<br>
                                            {% endfor %}
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-10">
                            {{ block('filtro') }}
                        </div>
                    </div>
                </div>
                <div class="table-responsive">
                    <table class="table table-sm mb-0">
                        <thead>
                            <tr class="table-info">
                                <th>{{ knp_pagination_sortable(personas, 'RUT', 'pp.run') }}</th>
                                <th>{{ knp_pagination_sortable(personas, 'Nombre', 'pp.nombres') }}</th>
                                <th>{{ knp_pagination_sortable(personas, 'Apellido Paterno', 'pp.apellidoPaterno') }}</th>
                                <th>{{ knp_pagination_sortable(personas, 'Apellido Materno', 'pp.apellidoMaterno') }}</th>
                                <th>{{ knp_pagination_sortable(personas, 'Nacimiento', 'pp.fechaNacimiento') }}</th>
                                <th>{{ knp_pagination_sortable(personas, 'Edad', 'pp.edad') }}</th>
                                <th>Calidad</th>
                                <th>Accidente</th>
                                <th class="text-center">Acciones</th>
                            </tr>
                        </thead>
                        <tbody>
                        {% for persona in personas %}
                            <tr>
                                <td>{{ persona.persona.run }}</td>
                                <td>{{ persona.persona.nombres }}</td>
                                <td>{{ persona.persona.apellidoPaterno }}</td>
                                <td>{{ persona.persona.apellidoMaterno }}</td>
                                <td>{{ persona.persona.fechaNacimiento|date('Y-m-d') }}</td>
                                <td>{{ persona.persona.edad|date('%y') }}</td>
                                <td>{{ persona.calidadPersonaAccidente }}</td>
                                <td>{{ persona.participacionPersonaAccidente }}</td>
{#}
                                <td>{{ persona.accidente ? persona.accidente.id : '' }}</td>
                                <td>{{ persona.accidente ? persona.accidente.fecha ? persona.accidente.fecha|date('Y-m-d') : '' }}</td>
                                <td>{{ persona.accidente ? persona.accidente.hora ? persona.accidente.hora|date('H:i') : '' }}</td>
{#}
                                <td class="text-center">
                                    <a class="btn btn-sm btn-light border-primary" href="{{ path('inspeccion_personaAccidente_editar', {'personaAccidente': persona.id}) }}" data-toggle="tooltip" data-placement="left" title data-original-title="Editar"><span class="fas fa-fw fa-edit"></span></a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                        <tfoot>
                            <tr>
                                <td colspan="8">Total: {{ personas|length }}</td>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
            <div class="d-flex justify-content-center">{{ knp_pagination_render(personas) }}</div>
        </div>
    </div>
{% endblock %}


templates/inspeccion/persona/layout.html.twig
{% extends 'inspeccion/layout.html.twig' %}

{% block inspeccion %}
    {% block persona %}{% endblock %}
{% endblock %}